// Permission constants
// WHY: Centralize permission strings to avoid typos and to make permission checks explicit.
export const PERMISSIONS = {
  INVITE_USER: "INVITE_USER",
  MANAGE_EMPLOYEE: "MANAGE_EMPLOYEE",
  MANAGE_BILLING: "MANAGE_BILLING",
  VIEW_BILLING: "VIEW_BILLING",
  GENERATE_REPORT: "GENERATE_REPORT",
  VIEW_REPORTS: "VIEW_REPORTS",
  PRINT_REPORT: "PRINT_REPORT",
  DISPATCH_REPORT: "DISPATCH_REPORT",
  ENQUEUE_PATIENT: "ENQUEUE_PATIENT",
  MANAGE_PATIENTS: "MANAGE_PATIENTS",
  MANAGE_SUBSCRIPTIONS: "MANAGE_SUBSCRIPTIONS",
  ADMINISTER_TENANT: "ADMINISTER_TENANT",
};

export default PERMISSIONS;
